name: chart-dynatrace-automation pipeline
trigger:
  branches:
    include:
    - refs/tags/*
pr:
  branches:
    include:
    - master
resources:
  repositories:
  - repository: cnp-library
    type: github
    ref: refs/heads/master
    name: hmcts/cnp-azuredevops-libraries
    endpoint: 'hmcts'

jobs:
- job: Validate
  pool:
    vmImage: 'Ubuntu 18.04'
  steps:
  - template: steps/charts/validate.yaml@cnp-library
    parameters:
      chartName: dynatrace-automation
      chartReleaseName: chart-dynatrace-automation-ci-test
      chartNamespace: chart-tests
      helmInstallTimeout: "500"

- job: Release
  # Make sure we have a tag to run this job
  condition: >
    and(
        succeeded(),
        startsWith(variables['Build.SourceBranch'], 'refs/tags/')
      )
  dependsOn: Validate
  pool:
    vmImage: 'Ubuntu 18.04'
  steps:
  - template: steps/charts/release.yaml@cnp-library
    parameters:
      chartName: dynatrace-automation
      chartReleaseName: chart-dynatrace-automation
      chartNamespace: chart-tests
