aadIdentityName: someId

testsConfig:
  keyVaults:
    "cmc":
      excludeEnvironmentSuffix: false
      secretRef: "kvcreds"
      secrets:
        smoke-test-citizen-username: SMOKE_TEST_CITIZEN_USER
        smoke-test-user-password: SMOKE_TEST_CITIZEN_PASS

smoketests:
  image: hmctspublic.azurecr.io/spring-boot/template-test
  enabled: true
  environment:
    TEST_URL: http://plum-recipe-backend-java
    TASK: smoke

functionaltests:
  image: hmctspublic.azurecr.io/spring-boot/template-test
  enabled: true
  environment:
    TEST_URL: http://plum-recipe-backend-java
    TASK: functional
