name: Chart Validate Pull Request
trigger:
  branches:
    include:
    - refs/tags/*
pr:
  branches:
    include:
    - master
variables:
  serviceConnection: azurerm-sandbox

jobs:
- job: ValidateChart
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - task: HelmInstaller@0
    inputs:
      helmVersion: '2.11.0'
      installKubectl: false

  - task: AzureCLI@1
    displayName: 'Lint and Test'
    inputs:
      azureSubscription: $(serviceConnection)
      scriptLocation: 'inlineScript'
      inlineScript: make ci-validate

  - script: make clean
    displayName: 'Cleanup'
    condition: always()