name: Chart Validate Pull Request
trigger: none
variables:
  serviceConnection: azurerm-sandbox
  release: 

jobs:
- job: RunBootstrap
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - task: HelmInstaller@0
    inputs:
      helmVersion: '2.11.0'
      installKubectl: false
  - task: AzureCLI@1
    displayName: 'Helm Package and Lint'
    inputs:
      azureSubscription: $(serviceConnection)
      scriptLocation: 'inlineScript'
      inlineScript: |
        make ci-validate
        #helm package java
        #helm lint java
        #az aks get-credentials --resource-group cnp-aks-sandbox-rg --name cnp-aks-sandbox-cluster
        #helm install java --name chart-java-release --namespace chart-tests --wait
        #helm test chart-java-release

  - script: make clean
    displayName: 'Cleanup'
    condition: always()


