name: Chart Validate Pull Request
trigger: refs/tags/*
variables:
  serviceConnection: azurerm-sandbox

jobs:
- job: RunBootstrap
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - task: HelmInstaller@0
    inputs:
      helmVersion: '2.11.0'
      installKubectl: false

  - task: AzureCLI@1
    displayName: 'Helm Package and Lint'
    inputs:
      azureSubscription: $(serviceConnection)
      scriptLocation: 'inlineScript'
      inlineScript: make ci-validate

  - script: make clean
    displayName: 'Cleanup'
    condition: always()