name: Chart Validate Pull Request
trigger: none
pr:
  branches:
    include:
    - master
resources:
  repositories:
  - repository: cnp-library
    type: github
    name: hmcts/cnp-azuredevops-libraries
    endpoint: 'HMCTS Github'

jobs:
- template: jobs/charts/validate.yaml@cnp-library
  parameters:
    serviceConnection: azurerm-sandbox
    acrName: hmctssandbox
    aksResourceGroup: cnp-aks-sandbox-rg
    aksCluster: cnp-aks-sandbox-cluster
    chartName: java
    chartReleaseName: chart-java-test
    chartNamespace: chart-tests