name: chart-java Release
trigger:
  branches:
    include:
    - refs/tags/*
pr: none
variables:
  serviceConnection: azurerm-sandbox

jobs:
- job: ReleaseChart
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - task: HelmInstaller@0
    inputs:
      helmVersion: '2.11.0'
      installKubectl: false

  - task: AzureCLI@1
    displayName: 'Package and Release'
    inputs:
      azureSubscription: $(serviceConnection)
      scriptLocation: 'inlineScript'
      inlineScript: make ci-release
