name: chart-java Release
trigger:
  branches:
    include:
    - refs/tags/*
pr: none
resources:
  repositories:
  - repository: cnp-library
    type: github
    name: hmcts/cnp-azuredevops-libraries
    endpoint: 'HMCTS Github'
jobs:
- template: jobs/charts/release.yaml@cnp-library
  parameters:
    chartName: java
    chartReleaseName: chart-java
    chartNamespace: chart-tests
