apiVersion: v2
description: A Helm chart for HMCTS Java Microservices
name: java
# This is the chart version. This doesn't need to be incremented on every change.
# It is managed by release pipeline based on Github tag
version: 0.1.0 # Do not change
appVersion: 0.1.0 # Do not change
type: application
icon: https://github.com/hmcts/chart-java/raw/master/images/icons8-java-50.png
keywords:
  - java
  - web
  - springboot
  - postgres
  - postgresql

dependencies:
  - name: library
    version: 2.2.2
    repository: oci://hmctsprod.azurecr.io/helm
  - name: postgresql
    version: 18.2.0
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
