apiVersion: v1
description: A Helm chart for HMCTS Java Microservices
name: java
version: 2.1.2
icon: https://github.com/hmcts/chart-java/raw/master/images/icons8-java-50.png
keywords:
- java
- web
- springboot
- postgres
- postgresql
