dependencies:
   - name: postgresql
     version: ~6.3.5
     repository: '@stable'
     condition: postgresql.enabled
   - name: job
     version: ~0.5.0
     repository: '@hmctspublic'
     alias: smokeTestsJob
     condition: smokeTestsJob.enabled
   - name: job
     version: ~0.5.0
     repository: '@hmctspublic'
     alias: functionalTestsJob
     condition: functionalTestsJob.enabled
   - name: job
     version: ~0.5.0
     repository: '@hmctspublic'
     alias: smokeTestsCronJob
     condition: smokeTestsCronJob.enabled
   - name: job
     version: ~0.5.0
     repository: '@hmctspublic'
     alias: functionalTestsCronJob
     condition: functionalTestsCronJob.enabled
