dependencies:
   - name: postgresql
     version: ~6.3.5
     repository: '@stable'
     condition: postgresql.enabled
   - name: job
     version: ~0.4.0
     repository: '@hmctspublic'
     alias: tests.smoke.once
     condition: tests.smoke.once.enabled
   - name: job
     version: ~0.4.0
     repository: '@hmctspublic'
     alias: tests.functional.once
     condition: tests.functional.once.enabled
   - name: job
     version: ~0.4.0
     repository: '@hmctspublic'
     alias: tests.smoke.cron
     condition: tests.smoke.cron.enabled
   - name: job
     version: ~0.4.0
     repository: '@hmctspublic'
     alias: tests.functional.cron
     condition: tests.functional.cron.enabled
