dependencies:
   - name: postgresql
     version: ~6.3.5
     repository: '@stable'
     condition: postgresql.enabled
   - name: job
     version: ~0.3.0
     repository: '@hmctspublic'
     alias: tests.smoke
     condition: tests.smoke.enabled
   - name: job
     version: ~0.3.0
     repository: '@hmctspublic'
     alias: tests.functional
     condition: tests.functional.enabled
