{{ if .Values.smoketests.enabled }}
---
{{ $smokedata := dict "Values" .Values "Release" .Release "Chart" .Chart }}
{{ $_ := set $smokedata.Values "task" "smoke" }}
{{- include "java.tests.metadata" $smokedata | nindent 2 }}
spec:
{{ $_ := set $smokedata.Values "tests" .Values.smoketests }}
{{- include "java.tests.spec" $smokedata | nindent 2 }}
{{- end }}
{{ if .Values.functionaltests.enabled }}
---
{{ $functionaldata := dict "Values" .Values "Release" .Release "Chart" .Chart }}
{{ $_ := set $functionaldata.Values "task" "functional" }}
{{- include "java.tests.metadata" $functionaldata | nindent 2 }}
spec:
{{ $_ := set $functionaldata.Values "tests" .Values.functionaltests }}
{{- include "java.tests.spec" $functionaldata | nindent 2 }}
{{- end }}