{{ if .Values.smoketests.enabled }}
---
{{ $smokedata := dict "Values" .Values "Release" .Release "Chart" .Chart }}
{{ $_ := set $smokedata.Values "task" "smoke" }}
{{ $_ := set $smokedata.Values "type" "tests" }}
{{- include "java.tests.header" $smokedata }}
spec:
{{ $_ := set $smokedata.Values "tests" .Values.smoketests }}
{{- include "java.tests.spec" $smokedata | indent 2 }}
{{- end }}

{{ if .Values.functionaltests.enabled }}
---
{{ $functionaldata := dict "Values" .Values "Release" .Release "Chart" .Chart }}
{{ $_ := set $functionaldata.Values "task" "functional" }}
{{ $_ := set $functionaldata.Values "type" "tests" }}
{{- include "java.tests.header" $functionaldata }}
spec:
{{ $_ := set $functionaldata.Values "tests" .Values.functionaltests }}
{{- include "java.tests.spec" $functionaldata | indent 2 }}
{{- end }}

{{ if .Values.smoketestscron.enabled }}
---
{{ $smokedatacron := dict "Values" .Values "Release" .Release "Chart" .Chart }}
{{ $_ := set $smokedatacron.Values "task" "smoke" }}
{{ $_ := set $smokedatacron.Values "schedule" .Values.smoketestscron.schedule }}
{{ $_ := set $smokedatacron.Values "type" "testscron" }}
{{- include "java.testscron.header" $smokedatacron }}
{{ "spec:" | indent 6 }}
{{ $_ := set $smokedatacron.Values "tests" .Values.smoketestscron }}
{{- include "java.tests.spec" $smokedatacron | indent 8 }}
{{- end }}

{{ if .Values.functionaltestscron.enabled }}
---
{{ $functionaldatacron := dict "Values" .Values "Release" .Release "Chart" .Chart }}
{{ $_ := set $functionaldatacron.Values "task" "functional" }}
{{ $_ := set $functionaldatacron.Values "schedule" .Values.functionaltestscron.schedule }}
{{ $_ := set $functionaldatacron.Values "type" "testscron" }}
{{- include "java.testscron.header" $functionaldatacron }}
{{ "spec:" | indent 6 }}
{{ $_ := set $functionaldatacron.Values "tests" .Values.functionaltestscron }}
{{- include "java.tests.spec" $functionaldatacron | indent 8 }}
{{- end }}
