{{ if .Values.smoketests.enabled }}
---
apiVersion: v1
kind: Pod
metadata:
  name: smoketests-job
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}-smoketests
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/name: {{ template "hmcts.java.releaseName" . }}-smoketests
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation 
spec:
  restartPolicy: Never
  containers:
    - name: smoketests
      image: {{ .Values.smoketests.image }}
{{- end }}
{{ if .Values.functionaltests.enabled }}
---
apiVersion: v1
kind: Pod
metadata:
  name: functionaltests-job
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}-functionaltests
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/name: {{ template "hmcts.java.releaseName" . }}-functionaltests
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation # preserve job pod but delete before next install/upgrade
spec:
  restartPolicy: Never
  containers:
    - name: smoketests
      image: {{ .Values.functionaltests.image }}
{{- end }}