---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "hmcts.releaseName" . }}
  labels:
    app.kubernetes.io/name: {{ template "hmcts.releaseName" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ template "hmcts.releaseName" . }}
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: {{ .Values.applicationPort }}
  selector:
    app.kubernetes.io/name: {{ template "hmcts.releaseName" . }}