---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "hmcts.java.releaseName" . }}
  labels:
    {{- ( include "java.labels" . ) | indent 4 }}
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: {{ .Values.applicationPort }}
  selector:
    app.kubernetes.io/name: {{ template "hmcts.java.releaseName" . }}